In [38]:
import cv2 as cv
import numpy as np

In [39]:
# Load Video
cap = cv.VideoCapture('inputVideos/video_01.mp4')

In [40]:
# Get Frame
ret, frame = cap.read()

In [41]:
# Draw Polygon
contours1 = np.array([[237,180],[297,180],[424,550],[255,542]], np.int32).reshape((-1,1,2))
contours2 = np.array([[255,543],[424,551],[459,645],[258,630]], np.int32).reshape((-1,1,2))

contours3 = np.array([[298,180],[350,180],[590,562],[425,550]], np.int32).reshape((-1,1,2))
contours4 = np.array([[425,550],[590,562],[650,658],[460,645]], np.int32).reshape((-1,1,2))

contours5 = np.array([[385,230],[448,230],[750,574],[591,561]], np.int32).reshape((-1,1,2))


frame = cv.polylines(frame,[contours1, contours2, contours3, contours4, contours5 ],True,(0,255,0),2,cv.LINE_AA)

frame = cv.putText(frame, "1", (257, 200), cv.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)
frame = cv.putText(frame, "2", (315, 563), cv.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)
frame = cv.putText(frame, "3", (320, 200), cv.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)
frame = cv.putText(frame, "4", (445, 570), cv.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)
frame = cv.putText(frame, "5", (405, 250), cv.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)

In [42]:
# Show Image
cv.imshow('image', frame)
cv.waitKey(1) 
cv.destroyAllWindows()

In [43]:
# Close the image
cv.waitKey(1) 

-1

In [44]:
# Checking the pointPolygonTest function
print("Inside (257, 200) Point: ", cv.pointPolygonTest(contours1, (257, 200), False) )
print("In the Contour (237,180) Point: ", cv.pointPolygonTest(contours1, (237,180), False) )
print("Outside (100, 100) Point: ", cv.pointPolygonTest(contours1, (100, 100), False) )

Inside (257, 200) Point:  1.0
In the Contour (237,180) Point:  0.0
Outside (100, 100) Point:  -1.0


In [45]:
contours = [np.array([[237,180],[297,180],[424,550],[255,542]], np.int32).reshape((-1,1,2)),
np.array([[255,543],[424,551],[459,645],[258,630]], np.int32).reshape((-1,1,2)),
np.array([[298,180],[350,180],[590,562],[425,550]], np.int32).reshape((-1,1,2)),
np.array([[425,550],[590,562],[650,658],[460,645]], np.int32).reshape((-1,1,2)),
np.array([[385,230],[448,230],[750,574],[591,561]], np.int32).reshape((-1,1,2))]

In [59]:
## Factors for Speed Estimation / Approximation

In [60]:
contours[0]

array([[[237, 180]],

       [[297, 180]],

       [[424, 550]],

       [[255, 542]]], dtype=int32)

In [61]:
factor_contour = contours[0]
contours[0][3] - contours[0][0]

array([[ 18, 362]], dtype=int32)

In [62]:
contours[0][2] - contours[0][1]

array([[127, 370]], dtype=int32)

In [63]:
(contours[0][3] - contours[0][0] + contours[0][2] - contours[0][1]) / 2

array([[ 72.5, 366. ]])

In [64]:
c_idx=0
((contours[c_idx][3] - contours[c_idx][0] + contours[c_idx][2] - contours[c_idx][1]) / 2)[0][1]

366.0

In [65]:
c_idx=0
feet_per_mile = 5280
c_y_feet = [ 289, 2, 287, 2, 207]   # As per provided drawing
factors = []

for c_idx in range(5): 
    c_y_pixels = ((contours[c_idx][3] - contours[c_idx][0] + contours[c_idx][2] - contours[c_idx][1]) / 2)[0][1]
    factors.append(c_y_feet[c_idx] / (c_y_pixels * feet_per_mile))

factors

[0.00014954876635204505,
 4.185501423070484e-06,
 0.00014456399097356545,
 3.966365222909725e-06,
 0.00011616161616161616]

In [82]:
contour_factors = [0.00014954876635204505, 4.185501423070484e-06, 0.00014456399097356545, 3.966365222909725e-06, 0.00011616161616161616]

In [93]:
np.array(contour_factors) * 29 * 3600

array([15.61289121,  0.43696635, 15.09248066,  0.41408853, 12.12727273])